# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

['Hi', 'there', 'Sam!']


In [ ]:
s = "Hi there Sam!"
p=s.split()
print(p)

['Hi', 'there', 'Sam!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

The diameter of Earth is 12742 kilometers


In [ ]:
planet = "Earth"
diameter = 12742
print("The diameter of",planet,"is",diameter,"kilometers")

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]



'hello'

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
array=np.ones(10)*5
print("An array of 10 five:")
print(array)

An array of 10 five:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
array=np.arange(20,36,2)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
from numpy.matrixlib.defmatrix import concatenate
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=np.concatenate((a, b))
print(c)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
, indexes
from tables import Column
import numpy as np
col=['a','b']
index=['c','d','e']
values=[[1,2],[3,4],[5,6]]
c=pd.DataFrame(values, columns =col, index=index)
print(c)

   a  b
c  1  2
d  3  4
e  5  6


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import pandas as pd
import numpy as np  
a=np.arange(1,32)
b=np.arange(1,11)
labels=('Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023','Jan,2023')
labels2=('Feb 2023','Feb 2023','Feb 2023','Feb 2023','Feb 2023','Feb 2023','Feb 2023','Feb 2023','Feb 2023','Feb 2023',)
c=pd.Series(data=a, index=labels)
d=pd.Series(data=b, index=labels2)

print(c,d)


Jan,2023     1
Jan,2023     2
Jan,2023     3
Jan,2023     4
Jan,2023     5
Jan,2023     6
Jan,2023     7
Jan,2023     8
Jan,2023     9
Jan,2023    10
Jan,2023    11
Jan,2023    12
Jan,2023    13
Jan,2023    14
Jan,2023    15
Jan,2023    16
Jan,2023    17
Jan,2023    18
Jan,2023    19
Jan,2023    20
Jan,2023    21
Jan,2023    22
Jan,2023    23
Jan,2023    24
Jan,2023    25
Jan,2023    26
Jan,2023    27
Jan,2023    28
Jan,2023    29
Jan,2023    30
Jan,2023    31
dtype: int64 Feb 2023     1
Feb 2023     2
Feb 2023     3
Feb 2023     4
Feb 2023     5
Feb 2023     6
Feb 2023     7
Feb 2023     8
Feb 2023     9
Feb 2023    10
dtype: int64


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
#lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
import pandas as pd

In [ ]:
col=['a','b','c']
index=['1','2','3']
values=[[1,2,3],['aaa','bbb','ccc'],[22,25,24]]
c=pd.DataFrame(values, columns= col, index=index)
print(c)

     a    b    c
1    1    2    3
2  aaa  bbb  ccc
3   22   25   24
